'use client';

import { useState } from 'react';
import { checkMisinformation, MisinformationCheckerOutput } from '@/ai/flows/misinformation-checker-flow';
import { Card, CardContent, CardHeader, CardTitle, CardDescription, CardFooter } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { ShieldAlert, ShieldCheck, Loader2, AlertTriangle } from 'lucide-react';
import { cn } from '@/lib/utils';

export function MisinfoChecker() {
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<MisinformationCheckerOutput | null>(null);

  const handleCheck = async () => {
    if (!input.trim()) return;
    setLoading(true);
    try {
      const res = await checkMisinformation({ information: input });
      setResult(res);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      <Card className="border-none shadow-md">
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <ShieldCheck className="w-6 h-6 text-primary" />
            Fact Checker
          </CardTitle>
          <CardDescription>Paste news articles or social media posts to verify their accuracy.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <Textarea 
            placeholder="Paste text here..." 
            className="min-h-[150px] resize-none"
            value={input}
            onChange={(e) => setInput(e.target.value)}
          />
          <Button 
            className="w-full h-12 bg-primary text-lg" 
            onClick={handleCheck}
            disabled={loading || !input.trim()}
          >
            {loading ? <Loader2 className="animate-spin mr-2" /> : <ShieldAlert className="mr-2 w-5 h-5" />}
            Analyze Information
          </Button>
        </CardContent>
      </Card>

      {result && (
        <Card className={cn(
          "border-l-4 shadow-lg animate-in fade-in slide-in-from-top-2",
          result.isMisinformation ? "border-l-destructive" : "border-l-success"
        )}>
          <CardHeader>
            <div className="flex justify-between items-start">
              <div>
                <CardTitle className="text-xl mb-1">
                  {result.isMisinformation ? "Potential Misinformation" : "Likely Accurate"}
                </CardTitle>
                <CardDescription>Assessment generated by AI</CardDescription>
              </div>
              <Badge variant={result.isMisinformation ? "destructive" : "default"} className="px-3 py-1">
                Confidence: {result.confidenceScore}%
              </Badge>
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            {result.isMisinformation && (
              <div className="bg-destructive/10 p-3 rounded-lg flex gap-3 text-destructive">
                <AlertTriangle className="w-5 h-5 shrink-0" />
                <p className="text-sm font-medium">Caution: This content may contain misleading information.</p>
              </div>
            )}
            <div className="text-muted-foreground leading-relaxed italic">
              "{input.length > 100 ? input.substring(0, 100) + '...' : input}"
            </div>
            <div className="prose prose-sm dark:prose-invert">
              <p className="text-foreground leading-relaxed">{result.explanation}</p>
            </div>
          </CardContent>
          <CardFooter className="text-[10px] text-muted-foreground">
            Disclaimer: AI tools can make mistakes. Always cross-verify with trusted local election officials.
          </CardFooter>
        </Card>
      )}
    </div>
  );
}